# Generated by Django 4.1.1 on 2022-12-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_useraddotionalinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddotionalInfo',
            new_name='UserAdditionalInfo',
        ),
    ]
